import type {
  Addon,
  AnalyticsOverviewRow,
  AnalyticsSummary,
  App,
  BackupConfig,
  BackupInfo,
  CronJob,
  DbColumn,
  DbQueryResult,
  DeploymentRecord,
  GitHubContent,
  NotificationConfig,
  PerAppMetrics,
  ProjectDetail,
  ProjectSummary,
  Server,
  SystemVersion,
  UpdateProgress,
  UpdateStatus,
  Vulnerability,
} from "./types"

export { DEMO_CATALOG } from "./demo-catalog.generated"

const now = Date.now()
export const DEMO_DOMAIN = "better-paas.com"
export const ago = (minutes: number) => new Date(now - minutes * 60_000).toISOString()

/** Per-service domains for non-running states (preview not shown for these). */
const DEMO_STATUS_DOMAINS: Record<string, string> = {
  "app-api": "api.better-paas.com",
  "app-embeddings": "embeddings.better-paas.com",
  "app-cron": "cron.better-paas.com",
}

function demoDomainForApp(app: App): string {
  if (app.status === "building" || app.status === "failed") {
    return DEMO_STATUS_DOMAINS[app.id] ?? `${app.name}.better-paas.com`
  }
  return DEMO_DOMAIN
}

function withDemoUrl(app: App): App {
  const domain = demoDomainForApp(app)
  return { ...app, url: domain, domains: [domain] }
}

export const DEMO_SERVERS: Server[] = [
  {
    id: "localhost",
    name: "Localhost",
    description: "This machine",
    ip: "127.0.0.1",
    port: 22,
    sshUser: "root",
    isLocal: true,
    status: "connected",
    lastChecked: ago(0),
    createdAt: ago(60 * 24 * 30),
  },
  {
    id: "srv-prod-01",
    name: "prod-vps-01",
    description: "Production VPS",
    ip: "203.0.113.42",
    port: 22,
    sshUser: "deploy",
    isLocal: false,
    status: "connected",
    lastChecked: ago(1),
    createdAt: ago(60 * 24 * 14),
  },
]

const DEMO_APPS_INTERNAL: App[] = [
  {
    id: "app-storefront",
    name: "storefront-web",
    status: "running",
    gitRepo: "acme/storefront",
    branch: "main",
    port: 3000,
    url: "shop.better-paas.com",
    createdAt: ago(60 * 24 * 30),
    buildMethod: "nixpacks",
    domains: ["shop.better-paas.com"],
    projectId: "proj-acme",
    serviceName: "storefront-web",
    activeCommit: "a1b2c3d",
    activeCommitMsg: "feat: checkout v2 redesign",
    activeDeployId: "dep-1042",
    envVars: { NODE_ENV: "production", DATABASE_URL: "postgres://..." },
    secretKeys: ["DATABASE_URL", "STRIPE_KEY"],
    autoDeploy: true,
    serverId: "localhost",
    vulnerabilitiesCount: 0,
  },
  {
    id: "app-api",
    name: "api-gateway",
    status: "building",
    gitRepo: "acme/api-gateway",
    branch: "main",
    port: 8080,
    url: "api.better-paas.com",
    createdAt: ago(60 * 24 * 20),
    buildMethod: "nixpacks",
    domains: ["api.better-paas.com"],
    projectId: "proj-acme",
    serviceName: "api-gateway",
    activeCommit: "d4e5f6a",
    activeCommitMsg: "feat: add per-route rate limiting",
    serverId: "localhost",
  },
  {
    id: "app-docs",
    name: "docs-site",
    status: "running",
    gitRepo: "acme/docs",
    branch: "main",
    port: 3000,
    url: "docs.better-paas.com",
    createdAt: ago(60 * 24 * 10),
    buildMethod: "nixpacks",
    domains: ["docs.better-paas.com"],
    projectId: "proj-acme",
    serviceName: "docs-site",
    activeCommit: "b2c3d4e",
    activeCommitMsg: "docs: update deploy guide",
    serverId: "localhost",
  },
  {
    id: "app-analytics",
    name: "analytics-edge",
    status: "running",
    gitRepo: "acme/edge",
    branch: "main",
    port: 8787,
    url: "stats.better-paas.com",
    createdAt: ago(60 * 24 * 5),
    buildMethod: "nixpacks",
    domains: ["stats.better-paas.com"],
    projectId: "proj-acme",
    serviceName: "analytics-edge",
    activeCommit: "c3d4e5f",
    activeCommitMsg: "perf: cache geo lookups",
    serverId: "localhost",
  },
  {
    id: "app-billing",
    name: "worker-billing",
    status: "stopped",
    gitRepo: "acme/billing",
    branch: "release",
    port: 4000,
    url: "billing.better-paas.com",
    createdAt: ago(60 * 24 * 45),
    buildMethod: "nixpacks",
    domains: ["billing.better-paas.com"],
    projectId: "proj-internal",
    serviceName: "worker-billing",
    activeCommit: "e5f6a7b",
    activeCommitMsg: "chore: bump stripe sdk",
    serverId: "localhost",
  },
  {
    id: "app-cron",
    name: "legacy-cron",
    status: "failed",
    gitRepo: "acme/cron",
    branch: "main",
    port: 3000,
    url: "cron.better-paas.com",
    createdAt: ago(60 * 24 * 60),
    buildMethod: "nixpacks",
    domains: ["cron.better-paas.com"],
    projectId: "proj-internal",
    serviceName: "legacy-cron",
    activeCommit: "f6a7b8c",
    activeCommitMsg: "fix: timezone in digest job",
    serverId: "localhost",
  },
  {
    id: "app-auth",
    name: "auth-service",
    status: "running",
    gitRepo: "acme/auth",
    branch: "main",
    port: 8081,
    url: "auth.better-paas.com",
    createdAt: ago(60 * 24 * 28),
    buildMethod: "nixpacks",
    domains: ["auth.better-paas.com"],
    projectId: "proj-acme",
    serviceName: "auth-service",
    activeCommit: "1a2b3c4",
    activeCommitMsg: "feat: passkey login support",
    autoDeploy: true,
    serverId: "localhost",
  },
  {
    id: "app-notify",
    name: "notification-worker",
    status: "running",
    gitRepo: "acme/notifications",
    branch: "main",
    port: 4001,
    url: "notify.better-paas.com",
    createdAt: ago(60 * 24 * 22),
    buildMethod: "nixpacks",
    domains: ["notify.better-paas.com"],
    projectId: "proj-acme",
    serviceName: "notification-worker",
    activeCommit: "2b3c4d5",
    activeCommitMsg: "fix: retry failed email deliveries",
    serverId: "localhost",
  },
  {
    id: "app-marketing",
    name: "marketing-web",
    status: "running",
    gitRepo: "acme/marketing",
    branch: "main",
    port: 3000,
    url: "better-paas.com",
    createdAt: ago(60 * 24 * 40),
    buildMethod: "nixpacks",
    domains: ["better-paas.com", "www.better-paas.com"],
    projectId: "proj-marketing",
    serviceName: "marketing-web",
    activeCommit: "3c4d5e6",
    activeCommitMsg: "content: refresh pricing page",
    autoDeploy: true,
    serverId: "localhost",
  },
  {
    id: "app-blog",
    name: "company-blog",
    status: "running",
    gitRepo: "acme/blog",
    branch: "main",
    port: 3000,
    url: "blog.better-paas.com",
    createdAt: ago(60 * 24 * 35),
    buildMethod: "nixpacks",
    domains: ["blog.better-paas.com"],
    projectId: "proj-marketing",
    serviceName: "company-blog",
    activeCommit: "4d5e6f7",
    activeCommitMsg: "post: self-hosting guide",
    serverId: "localhost",
  },
  {
    id: "app-status",
    name: "status-page",
    status: "running",
    gitRepo: "",
    branch: "",
    port: 3001,
    url: "status.better-paas.com",
    createdAt: ago(60 * 24 * 15),
    buildMethod: "catalog",
    catalogId: "uptime-kuma",
    domains: ["status.better-paas.com"],
    projectId: "proj-marketing",
    serviceName: "status-page",
    serverId: "localhost",
  },
  {
    id: "app-agent",
    name: "agent-orchestrator",
    status: "running",
    gitRepo: "acme/agents",
    branch: "main",
    port: 8000,
    url: "agents.better-paas.com",
    createdAt: ago(60 * 24 * 12),
    buildMethod: "nixpacks",
    domains: ["agents.better-paas.com"],
    projectId: "proj-ai",
    serviceName: "agent-orchestrator",
    activeCommit: "5e6f7a8",
    activeCommitMsg: "feat: tool-calling pipeline v2",
    autoDeploy: true,
    serverId: "localhost",
    vulnerabilitiesCount: 1,
  },
  {
    id: "app-chat",
    name: "chat-api",
    status: "running",
    gitRepo: "acme/chat-api",
    branch: "main",
    port: 8082,
    url: "chat.better-paas.com",
    createdAt: ago(60 * 24 * 11),
    buildMethod: "nixpacks",
    domains: ["chat.better-paas.com"],
    projectId: "proj-ai",
    serviceName: "chat-api",
    activeCommit: "6f7a8b9",
    activeCommitMsg: "perf: stream tokens over SSE",
    serverId: "localhost",
  },
  {
    id: "app-embeddings",
    name: "embeddings-worker",
    status: "building",
    gitRepo: "acme/embeddings",
    branch: "main",
    port: 8090,
    url: "embeddings.better-paas.com",
    createdAt: ago(60 * 24 * 8),
    buildMethod: "nixpacks",
    domains: ["embeddings.better-paas.com"],
    projectId: "proj-ai",
    serviceName: "embeddings-worker",
    activeCommit: "7a8b9c0",
    activeCommitMsg: "feat: batch embedding queue",
    serverId: "localhost",
  },
  {
    id: "app-staging-api",
    name: "staging-api",
    status: "running",
    gitRepo: "acme/api-gateway",
    branch: "develop",
    port: 8080,
    url: "staging-api.better-paas.com",
    createdAt: ago(60 * 24 * 7),
    buildMethod: "nixpacks",
    domains: ["staging-api.better-paas.com"],
    projectId: "proj-staging",
    serviceName: "staging-api",
    activeCommit: "8b9c0d1",
    activeCommitMsg: "chore: sync main into develop",
    serverId: "srv-prod-01",
  },
  {
    id: "app-staging-web",
    name: "staging-web",
    status: "stopped",
    gitRepo: "acme/storefront",
    branch: "develop",
    port: 3000,
    url: "staging.better-paas.com",
    createdAt: ago(60 * 24 * 7),
    buildMethod: "nixpacks",
    domains: ["staging.better-paas.com"],
    projectId: "proj-staging",
    serviceName: "staging-web",
    activeCommit: "9c0d1e2",
    activeCommitMsg: "wip: checkout experiments",
    serverId: "srv-prod-01",
  },
  {
    id: "app-n8n",
    name: "workflow-n8n",
    status: "running",
    gitRepo: "",
    branch: "",
    port: 5678,
    url: "n8n.better-paas.com",
    createdAt: ago(60 * 24 * 20),
    buildMethod: "catalog",
    catalogId: "n8n",
    domains: ["n8n.better-paas.com"],
    projectId: "proj-ops",
    serviceName: "workflow-n8n",
    serverId: "localhost",
  },
  {
    id: "app-wiki",
    name: "internal-wiki",
    status: "running",
    gitRepo: "",
    branch: "",
    port: 3000,
    url: "wiki.better-paas.com",
    createdAt: ago(60 * 24 * 25),
    buildMethod: "catalog",
    catalogId: "wikijs",
    domains: ["wiki.better-paas.com"],
    projectId: "proj-ops",
    serviceName: "internal-wiki",
    serverId: "localhost",
  },
  {
    id: "app-monitoring",
    name: "uptime-monitor",
    status: "running",
    gitRepo: "",
    branch: "",
    port: 3001,
    url: "monitor.better-paas.com",
    createdAt: ago(60 * 24 * 18),
    buildMethod: "catalog",
    catalogId: "uptime-kuma",
    domains: ["monitor.better-paas.com"],
    projectId: "proj-ops",
    serviceName: "uptime-monitor",
    serverId: "localhost",
  },
  {
    id: "app-pipeline",
    name: "data-pipeline",
    status: "stopped",
    gitRepo: "acme/pipeline",
    branch: "main",
    port: 5000,
    url: "pipeline.better-paas.com",
    createdAt: ago(60 * 24 * 50),
    buildMethod: "nixpacks",
    domains: ["pipeline.better-paas.com"],
    projectId: "proj-internal",
    serviceName: "data-pipeline",
    activeCommit: "0d1e2f3",
    activeCommitMsg: "chore: pause nightly ETL",
    serverId: "localhost",
  },
]

export const DEMO_APPS: App[] = DEMO_APPS_INTERNAL.map(withDemoUrl)

export const DEMO_PROJECTS: ProjectSummary[] = [
  {
    id: "proj-acme",
    name: "Acme Platform",
    description: "Core product services",
    createdAt: ago(60 * 24 * 45),
    serverId: "localhost",
    serviceCount: 6,
    status: "running",
    hasGit: true,
    lastServiceAt: ago(2),
    focusServiceId: "app-storefront",
    serviceStatuses: DEMO_APPS.filter((a) => a.projectId === "proj-acme").map((a) => ({
      id: a.id,
      name: a.name,
      status: a.status,
    })),
  },
  {
    id: "proj-marketing",
    name: "Marketing & Brand",
    description: "Public website, blog, and status page",
    createdAt: ago(60 * 24 * 40),
    serverId: "localhost",
    serviceCount: 3,
    status: "running",
    hasGit: true,
    hasDocker: true,
    lastServiceAt: ago(45),
    focusServiceId: "app-marketing",
    serviceStatuses: DEMO_APPS.filter((a) => a.projectId === "proj-marketing").map((a) => ({
      id: a.id,
      name: a.name,
      status: a.status,
    })),
  },
  {
    id: "proj-ai",
    name: "AI Agents",
    description: "Agent orchestration, chat API, and embedding workers",
    createdAt: ago(60 * 24 * 12),
    serverId: "localhost",
    serviceCount: 3,
    status: "building",
    hasGit: true,
    lastServiceAt: ago(3),
    focusServiceId: "app-agent",
    serviceStatuses: DEMO_APPS.filter((a) => a.projectId === "proj-ai").map((a) => ({
      id: a.id,
      name: a.name,
      status: a.status,
    })),
  },
  {
    id: "proj-staging",
    name: "Staging Environment",
    description: "Pre-production deploys on prod-vps-01",
    createdAt: ago(60 * 24 * 7),
    serverId: "srv-prod-01",
    serviceCount: 2,
    status: "running",
    hasGit: true,
    lastServiceAt: ago(120),
    focusServiceId: "app-staging-api",
    serviceStatuses: DEMO_APPS.filter((a) => a.projectId === "proj-staging").map((a) => ({
      id: a.id,
      name: a.name,
      status: a.status,
    })),
  },
  {
    id: "proj-ops",
    name: "Ops Stack",
    description: "One-click catalog apps for internal tooling",
    createdAt: ago(60 * 24 * 25),
    serverId: "localhost",
    serviceCount: 3,
    status: "running",
    hasDocker: true,
    lastServiceAt: ago(60 * 24),
    focusServiceId: "app-n8n",
    serviceStatuses: DEMO_APPS.filter((a) => a.projectId === "proj-ops").map((a) => ({
      id: a.id,
      name: a.name,
      status: a.status,
    })),
  },
  {
    id: "proj-internal",
    name: "Internal Tools",
    description: "Background workers, cron jobs, and data pipelines",
    createdAt: ago(60 * 24 * 60),
    serverId: "localhost",
    serviceCount: 3,
    status: "failed",
    hasGit: true,
    lastServiceAt: ago(60 * 24 * 2),
    focusServiceId: "app-cron",
    serviceStatuses: DEMO_APPS.filter((a) => a.projectId === "proj-internal").map((a) => ({
      id: a.id,
      name: a.name,
      status: a.status,
    })),
  },
]

export const DEMO_DEPLOYMENTS: DeploymentRecord[] = [
  {
    id: "dep-1042",
    appId: "app-storefront",
    appName: "storefront-web",
    status: "success",
    logs: ["Building...", "Deploy complete"],
    createdAt: ago(2),
    duration: "1m 34s",
    commit: "a1b2c3d",
    commitMsg: "feat: checkout v2 redesign",
    trigger: "git-push",
  },
  {
    id: "dep-1041",
    appId: "app-storefront",
    appName: "storefront-web",
    status: "success",
    logs: ["Building...", "Deploy complete"],
    createdAt: ago(180),
    duration: "1m 12s",
    commit: "9z8y7x6",
    commitMsg: "fix: cart total rounding",
    trigger: "manual",
  },
  {
    id: "dep-1040",
    appId: "app-api",
    appName: "api-gateway",
    status: "success",
    logs: ["Building..."],
    createdAt: ago(5),
    duration: "2m 05s",
    commit: "d4e5f6a",
    commitMsg: "feat: add per-route rate limiting",
    trigger: "git-push",
  },
  {
    id: "dep-1039",
    appId: "app-agent",
    appName: "agent-orchestrator",
    status: "success",
    logs: ["Building...", "Health check passed"],
    createdAt: ago(90),
    duration: "1m 48s",
    commit: "5e6f7a8",
    commitMsg: "feat: tool-calling pipeline v2",
    trigger: "git-push",
  },
  {
    id: "dep-1038",
    appId: "app-marketing",
    appName: "marketing-web",
    status: "success",
    logs: ["Building...", "Deploy complete"],
    createdAt: ago(45),
    duration: "1m 22s",
    commit: "3c4d5e6",
    commitMsg: "content: refresh pricing page",
    trigger: "manual",
  },
  {
    id: "dep-1037",
    appId: "app-staging-api",
    appName: "staging-api",
    status: "success",
    logs: ["Building...", "Deploy complete"],
    createdAt: ago(120),
    duration: "1m 55s",
    commit: "8b9c0d1",
    commitMsg: "chore: sync main into develop",
    trigger: "git-push",
  },
]

export const DEMO_ADDONS: Addon[] = [
  {
    id: "addon-pg-storefront",
    type: "postgres",
    name: "storefront-db",
    containerName: "bp-addon-storefront-db",
    status: "running",
    volume: "storefront-db-data",
    port: 5432,
    connEnv: { DATABASE_URL: "postgres://demo:demo@storefront-db:5432/storefront" },
    attachedApps: ["app-storefront"],
    createdAt: ago(60 * 24 * 25),
    serverId: "localhost",
  },
  {
    id: "addon-redis-api",
    type: "redis",
    name: "api-cache",
    containerName: "bp-addon-api-cache",
    status: "running",
    volume: "api-cache-data",
    port: 6379,
    connEnv: { REDIS_URL: "redis://api-cache:6379" },
    attachedApps: ["app-api"],
    createdAt: ago(60 * 24 * 18),
    serverId: "localhost",
  },
  {
    id: "addon-pg-analytics",
    type: "postgres",
    name: "analytics-db",
    containerName: "bp-addon-analytics-db",
    status: "running",
    volume: "analytics-db-data",
    port: 5432,
    attachedApps: ["app-analytics"],
    createdAt: ago(60 * 24 * 5),
    serverId: "localhost",
  },
  {
    id: "addon-redis-chat",
    type: "redis",
    name: "chat-cache",
    containerName: "bp-addon-chat-cache",
    status: "running",
    volume: "chat-cache-data",
    port: 6379,
    connEnv: { REDIS_URL: "redis://chat-cache:6379" },
    attachedApps: ["app-chat"],
    createdAt: ago(60 * 24 * 10),
    serverId: "localhost",
  },
  {
    id: "addon-pg-agents",
    type: "postgres",
    name: "agents-db",
    containerName: "bp-addon-agents-db",
    status: "running",
    volume: "agents-db-data",
    port: 5432,
    attachedApps: ["app-agent", "app-embeddings"],
    createdAt: ago(60 * 24 * 11),
    serverId: "localhost",
  },
]

export const DEMO_CRON: CronJob[] = [
  {
    id: "cron-1",
    appId: "app-cron",
    appName: "legacy-cron",
    schedule: "0 8 * * *",
    command: "npm run digest",
    enabled: true,
    lastRun: ago(60 * 8),
    lastStatus: "success",
    createdAt: ago(60 * 24 * 30),
  },
  {
    id: "cron-2",
    appId: "app-storefront",
    appName: "storefront-web",
    schedule: "0 2 * * *",
    command: "npm run backup-db",
    enabled: true,
    lastRun: ago(60 * 14),
    lastStatus: "success",
    createdAt: ago(60 * 24 * 20),
  },
  {
    id: "cron-3",
    appId: "app-api",
    appName: "api-gateway",
    schedule: "*/15 * * * *",
    command: "node scripts/purge-cache.js",
    enabled: true,
    lastRun: ago(12),
    lastStatus: "success",
    createdAt: ago(60 * 24 * 10),
  },
  {
    id: "cron-4",
    appId: "app-agent",
    appName: "agent-orchestrator",
    schedule: "0 */4 * * *",
    command: "python scripts/reindex_docs.py",
    enabled: true,
    lastRun: ago(60 * 3),
    lastStatus: "success",
    createdAt: ago(60 * 24 * 8),
  },
  {
    id: "cron-5",
    appId: "app-pipeline",
    appName: "data-pipeline",
    schedule: "0 3 * * *",
    command: "python run_etl.py --full",
    enabled: false,
    lastRun: ago(60 * 24 * 3),
    lastStatus: "failed",
    createdAt: ago(60 * 24 * 40),
  },
]

export const DEMO_BACKUPS: BackupInfo[] = [
  { name: "backup-2026-06-14-0200", sizeBytes: 2_516_582_400, createdAt: ago(60 * 12) },
  { name: "backup-2026-06-13-0200", sizeBytes: 2_483_183_616, createdAt: ago(60 * 36) },
  { name: "backup-2026-06-12-0200", sizeBytes: 2_441_432_064, createdAt: ago(60 * 60) },
]

export const DEMO_BACKUP_CONFIG: BackupConfig = {
  autoEnabled: true,
  intervalHours: 24,
  retention: 7,
  includeDatabases: true,
  s3Enabled: false,
  s3Endpoint: "",
  s3Region: "",
  s3Bucket: "",
  s3Prefix: "",
  s3AccessKeyId: "",
}

export const DEMO_NOTIFICATIONS: NotificationConfig = {
  slackWebhookUrl: "https://hooks.slack.com/services/demo",
  genericUrl: "",
  onSuccess: true,
  onFailure: true,
}

export const DEMO_VULNERABILITIES: Vulnerability[] = [
  {
    severity: "moderate",
    package: "lodash",
    title: "Prototype pollution in lodash",
    range: "<4.17.21",
    url: "https://github.com/advisories/GHSA-xx",
  },
]

export const DEMO_GIT_REPOS = [
  {
    full_name: "acme/storefront",
    name: "storefront",
    clone_url: "https://github.com/acme/storefront.git",
    html_url: "https://github.com/acme/storefront",
    private: true,
    description: "Customer-facing storefront",
    updated_at: ago(2),
  },
  {
    full_name: "acme/api-gateway",
    name: "api-gateway",
    clone_url: "https://github.com/acme/api-gateway.git",
    html_url: "https://github.com/acme/api-gateway",
    private: true,
    description: "Public API gateway",
    updated_at: ago(5),
  },
  {
    full_name: "acme/docs",
    name: "docs",
    clone_url: "https://github.com/acme/docs.git",
    html_url: "https://github.com/acme/docs",
    private: false,
    description: "Documentation site",
    updated_at: ago(60),
  },
  {
    full_name: "acme/marketing",
    name: "marketing",
    clone_url: "https://github.com/acme/marketing.git",
    html_url: "https://github.com/acme/marketing",
    private: false,
    description: "Marketing website",
    updated_at: ago(45),
  },
  {
    full_name: "acme/agents",
    name: "agents",
    clone_url: "https://github.com/acme/agents.git",
    html_url: "https://github.com/acme/agents",
    private: true,
    description: "AI agent orchestrator",
    updated_at: ago(90),
  },
  {
    full_name: "acme/chat-api",
    name: "chat-api",
    clone_url: "https://github.com/acme/chat-api.git",
    html_url: "https://github.com/acme/chat-api",
    private: true,
    description: "Realtime chat API",
    updated_at: ago(30),
  },
]

export const DEMO_GIT_CONTENTS: GitHubContent[] = [
  { name: "package.json", path: "package.json", type: "file" },
  { name: "next.config.js", path: "next.config.js", type: "file" },
  { name: "src", path: "src", type: "dir" },
  { name: "public", path: "public", type: "dir" },
  { name: "README.md", path: "README.md", type: "file" },
]

export const DEMO_DB_TABLES = ["users", "products", "orders", "sessions"]

export const DEMO_DB_COLUMNS: DbColumn[] = [
  { name: "id", type: "integer", nullable: false, primaryKey: true, default: null },
  { name: "email", type: "varchar", nullable: false, primaryKey: false, default: null },
  { name: "name", type: "varchar", nullable: true, primaryKey: false, default: null },
  { name: "created_at", type: "timestamp", nullable: false, primaryKey: false, default: "now()" },
]

export const DEMO_DB_ROWS: DbQueryResult = {
  columns: ["id", "email", "name", "created_at"],
  rows: [
    ["1", "alice@better-paas.com", "Alice Chen", ago(60 * 24 * 30)],
    ["2", "bob@better-paas.com", "Bob Smith", ago(60 * 24 * 20)],
    ["3", "carol@better-paas.com", "Carol Jones", ago(60 * 24 * 5)],
  ],
  total: 1240,
}

export const DEMO_LOG_LINES = [
  { message: "GET /api/products 200 12ms", timestamp: ago(0) },
  { message: "GET /api/cart 200 8ms", timestamp: ago(0) },
  { message: "POST /api/checkout 201 245ms", timestamp: ago(0) },
  { message: "Webhook sent to billing service", timestamp: ago(0) },
  { message: "GET /health 200 2ms", timestamp: ago(0) },
]

export const DEMO_BUILD_LOG_LINES = [
  { message: "=== Detected Node.js project ===", timestamp: ago(5) },
  { message: "Installing dependencies with npm ci...", timestamp: ago(4) },
  { message: "Running build command: npm run build", timestamp: ago(3) },
  { message: "Build completed successfully", timestamp: ago(2) },
  { message: "Starting container...", timestamp: ago(1) },
]

export function demoAnalyticsSummary(appId: string): AnalyticsSummary {
  const app = DEMO_APPS.find((a) => a.id === appId) ?? DEMO_APPS[0]
  const days = 7
  const timeseries = Array.from({ length: days }, (_, i) => ({
    date: new Date(now - (days - 1 - i) * 86_400_000).toISOString().slice(0, 10),
    views: 800 + Math.floor(Math.random() * 400),
    visitors: 200 + Math.floor(Math.random() * 100),
  }))
  return {
    appId: app.id,
    appName: app.name,
    rangeDays: days,
    totalViews: timeseries.reduce((s, b) => s + b.views, 0),
    totalVisitors: timeseries.reduce((s, b) => s + b.visitors, 0),
    timeseries,
    topPages: [
      { label: "/", count: 4200 },
      { label: "/products", count: 2800 },
      { label: "/checkout", count: 890 },
    ],
    topReferrers: [
      { label: "google.com", count: 3100 },
      { label: "Direct", count: 2400 },
      { label: "news.ycombinator.com", count: 420 },
    ],
    browsers: [
      { label: "Chrome", count: 6200 },
      { label: "Safari", count: 2100 },
      { label: "Firefox", count: 890 },
    ],
    os: [
      { label: "macOS", count: 4100 },
      { label: "Windows", count: 3200 },
      { label: "Linux", count: 890 },
    ],
    devices: [
      { label: "Desktop", count: 7200 },
      { label: "Mobile", count: 2800 },
    ],
  }
}

export function demoAnalyticsOverview(): AnalyticsOverviewRow[] {
  return DEMO_APPS.filter((a) => a.status === "running" && a.url).map((a, i) => ({
    appId: a.id,
    appName: a.name,
    views: 3000 - i * 600,
    visitors: 800 - i * 150,
  }))
}

export function demoPerAppMetrics(): PerAppMetrics[] {
  return DEMO_APPS.filter((a) => a.status === "running").map((a) => ({
    appId: a.id,
    name: a.name,
    cpuPercent: 5 + Math.random() * 20,
    memUsageMb: 128 + Math.floor(Math.random() * 256),
    memLimitMb: 512,
    memPercent: 25 + Math.random() * 30,
    netRxMb: Math.random() * 10,
    netTxMb: Math.random() * 5,
  }))
}

export function demoProjectDetail(id: string): ProjectDetail | null {
  const project = DEMO_PROJECTS.find((p) => p.id === id)
  if (!project) return null
  return {
    ...project,
    services: DEMO_APPS.filter((a) => a.projectId === id),
  }
}

export const DEMO_SYSTEM_VERSION: SystemVersion = {
  version: "1.4.0",
  gitCheckout: false,
  updateRepo: "sumon-ohid/better-paas",
}

export const DEMO_UPDATE_STATUS: UpdateStatus = {
  current: "1.4.0",
  latest: "1.4.0",
  hasUpdate: false,
  configured: true,
  checkedAt: ago(60),
}

export const DEMO_UPDATE_PROGRESS: UpdateProgress = {
  state: "idle",
  inProgress: false,
  log: "",
}

export function getDemoApp(id: string): App | undefined {
  return DEMO_APPS.find((a) => a.id === id)
}
